services:
  postgres-core:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postechappcore
      POSTGRES_USER: postechadmin
      POSTGRES_PASSWORD: postechadmin
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postechadmin -d postechappcore']
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - postgres-core-data:/var/lib/postgresql/data

  postgres-sales:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postechappsales
      POSTGRES_USER: postechadmin
      POSTGRES_PASSWORD: postechadmin
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postechadmin -d postechappsales']
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - postgres-sales-data:/var/lib/postgresql/data

  core:
    build:
      context: .
    env_file:
      - .env
    environment:
      PORT: 3000
      SALES_SERVICE_URL: http://sales:4000/api
      SALES_SERVICE_TOKEN: local-sync-token
      DATABASE_HOST: postgres-core
      DATABASE_PORT: 5432
      DATABASE_NAME: postechappcore
      DATABASE_USER: postechadmin
      DATABASE_PASSWORD: postechadmin
      DATABASE_SSL: 'false'
    ports:
      - '3000:3000'
    depends_on:
      sales:
        condition: service_started
      postgres-core:
        condition: service_healthy

  sales:
    build:
      context: ../vehicle-sales-service
    env_file:
      - ../vehicle-sales-service/.env
    environment:
      PORT: 4000
      INTERNAL_SYNC_TOKEN: local-sync-token
      CORE_SERVICE_URL: http://core:3000/api
      CORE_SERVICE_TOKEN: local-sync-token
      DATABASE_HOST: postgres-sales
      DATABASE_PORT: 5432
      DATABASE_NAME: postechappsales
      DATABASE_USER: postechadmin
      DATABASE_PASSWORD: postechadmin
      DATABASE_SSL: 'false'
    ports:
      - '4000:4000'
    depends_on:
      postgres-sales:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --http-port=8080 --hostname-strict=false
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  keycloak-data:
    driver: local
  postgres-core-data:
    driver: local
  postgres-sales-data:
    driver: local
